# Generated by Django 4.0.4 on 2022-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_enquiry_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
