# Generated by Django 4.0.4 on 2022-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListCar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
