# Generated by Django 4.0.4 on 2022-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListCar', '0002_car_make_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
