# Generated by Django 4.0.4 on 2022-05-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListCar', '0004_alter_car_id_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller_name',
            field=models.CharField(max_length=30),
        ),
    ]
