# Generated by Django 4.0.4 on 2022-05-06 10:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ListCar', '0005_alter_car_make_alter_car_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
