# Generated by Django 4.0.4 on 2022-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListCar', '0006_alter_car_seller_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
